[project]
name = "sql-rag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-adk>=1.17.0",
    "psycopg2-binary>=2.9.11",
    "sqlglot[rs]>=27.29.0",
]
